title: Computer Sciencing Complex Systems
author: Anthony J. Clark and Jared M. Moore
description: A collection of posts from Drs. Clark and Moore and their students.

show_excerpts: false

theme: jekyll-theme-minimal

exclude: [post-template.md, CONTRIBUTING.md]

permalink: /:title:output_ext
